---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
engines:
  phan:
    enabled: true
    config:
      file_extensions: "php"
      backward-compatibility-checks: true
      dead-code-detection: true
exclude_paths:
  - tests/**/*
  - plugins/**/*
ratings:
  paths:
    - "**.php"
